-- --
-- require('formatter').setup({
--   logging = false,
--   filetype = {
--     javascript = formatter_prettier,
--     javascriptreact = formatter_prettier,
--     typescript = formatter_prettier,
--     typescriptreact = formatter_prettier,
--     json = formatter_prettier,
--     graphql = formatter_prettier
--   }
-- })

-- require("lsp-format").setup {
--   typescript = {
--       tab_width = function()
--           return vim.opt.shiftwidth:get()
--       end,
--   },
--   yaml = { tab_width = 2 },
-- }
--
-- local prettier = {
--   formatCommand = [[prettier --stdin-filepath ${INPUT} ${--tab-width:tab_width}]],
--   formatStdin = true,
-- }
--
-- require("lspconfig").efm.setup {
--   on_attach = require("lsp-format").on_attach,
--   init_options = { documentFormatting = true },
--   settings = {
--     languages = {
--       typescript = { prettier },
--       yaml = { prettier },
--
--     },
--   },
-- }

-- vim.api.nvim_exec([[
-- augroup FormatAutogroup
--   autocmd!
--   autocmd BufWritePost *.astro,*.ts,*.tsx,*.mjs,*.js,*.jsx,*.json,*.graphql FormatWrite
-- augroup END
-- ]], true)
--
-- vim.api.nvim_command("autocmd BufWritePre *.ex,*.go lua vim.lsp.buf.formatting()")
