require('plugins')
require('settings')
require('keymaps')
require('colors')

require('core_plugins.autopairs')
require('core_plugins.blame')
require('core_plugins.cmp')
require('core_plugins.comment')
require('core_plugins.copilot')
-- require('core_plugins.formatter')
require('core_plugins.gitsigns')
require('core_plugins.lsp-config')
require('core_plugins.lsp-diagnostics')
require('core_plugins.lualine')
require('core_plugins.nvim-tree')
require('core_plugins.telescope')
require('core_plugins.treesitter')
-- require('core_plugins.windline')
