require('plugins')
require('colors')
require('settings')
require('keymaps')

require('core_plugins.autopairs')
require('core_plugins.bookmark')
require('core_plugins.blame')
require('core_plugins.comment')
require('core_plugins.cmp')
require('core_plugins.copilot')
require('core_plugins.gitsigns')
-- require('core_plugins.fidget')
require('core_plugins.formatter')
require('core_plugins.hexokinase')
require('core_plugins.lsp')
require('core_plugins.lsp-diagnostics')
require('core_plugins.lspkind')
require('core_plugins.mason')
require('core_plugins.mini')
require('core_plugins.null')
require('core_plugins.nvim-tree')
-- require('core_plugins.nnn')
require('core_plugins.telescope')
require('core_plugins.template-string')
require('core_plugins.todo-comments')
require('core_plugins.treesitter')
